on:
  push:
    branches:
    - main
  workflow_dispatch:

name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: Install lftp
      shell: bash
      run: sudo apt install lftp
    - name: 📂 Sync files
      shell: bash
      run: lftp -u ${{ secrets.ftp_username }},${{ secrets.ftp_password }} -e "mirror -R www/ www/; quit" ftp://${{ secrets.ftp_server }}
